version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"  # Exponer el puerto 100 internamente en el contenedor
    volumes:
      - ./proyect-10:/usr/src/app
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Configuración personalizada de Nginx
    ports:
      - "100:100"
    depends_on:
      - app
